services:
    eslint: true

    composernormalize:
        version: latest

    phpcsfixer: false

    phpcs:
        version:     latest
        config_path: ~
        paths:       []
        composer:    true

    phpcbf:
        version:     latest
        config_path: ~
        paths:       []
        composer:    true

    shellcheck:
        version:     latest
        path:        .
