language: php

dist: trusty

sudo: false

services:
    - docker

addons:
    apt:
        packages:
            - docker-ce

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
          env: coverage=1 lint=1

before_install:
    - sudo service postgresql stop
    # wait for postgresql to shutdown
    - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
    - make install

script:
    - make lint test
